### ISSUE TITLE
oc_reader_preferences"."reader_preferences_file_id_index" is too long.

### ISSUE THREAD

**Issue by bohica70** [e-alfred/epubreader#23] opened 2020-10-22 11:32 UTC
I noticed the certificate issue was closed, so I am opening a new issue.

Nextcloud 19.04
EPUB/CBZ/PDF ebook reader 1.4.3

Cannot activate. I receive the following error:

Unable to proceed. Index name "oc_reader_preferences"."reader_preferences_file_id_index" is
too long.

![image](https://user-images.githubusercontent.com/55824222/96866022-f1539980-1427-11eb-8f57-fb363a13dad1.png)

**Comment by cpaucar3** [comment] 2020-10-24 03:17
I just installed a fresh Docker image of the latest version of Nextcloud 20. I also got this error when trying to add this app. Other apps install without issues.

**Comment by gaglegemaate** [comment] 2020-10-27 19:42
Same here. Downloading went fine, enabling results in the aforementioned error. Using a Docker (v20) snap on an Ubuntu server.

**Comment by deusoz** [comment] 2020-10-27 23:33
same here, git install of v19 on Centos

**Comment by nowjon** [comment] 2020-10-28 14:43
Same errors as above, fresh Nextcloud install on 19.03.5 Docker on UNRAID.

**Comment by infidelus** [comment] 2020-10-29 12:01
Another 'me too'.  Attempting to enable ebook reader 1.4.3 generates the above error.

**Comment by e-alfred** [comment] 2020-10-31 18:44
Thanks for your report, but this is a duplicate of https://github.com/e-alfred/epubreader/issues/18. Please add any additional information there.

**Closed by e-alfred** 2020-10-31 18:44 UTC

**Comment by bohica70** [comment] 2020-10-31 19:39
Is there a resolution for #18?

------ Original Message ------
